
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.crossing.bridgecrossingws;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.2
 * 2015-09-10T16:49:40.081+01:00
 * Generated source version: 3.1.2
 * 
 */

@javax.jws.WebService(
                      serviceName = "BridgeCrossingWS",
                      portName = "BridgeCrossingPort",
                      targetNamespace = "http://www.crossing.com/BridgeCrossingWS/",
                      wsdlLocation = "file:/C:/Work/Workspaces/eclipselunaworkspace/WSForMule/WebContent/wsdl/BridgeCrossingPort.wsdl",
                      endpointInterface = "com.crossing.bridgecrossingws.BridgeCrossingWS")
                      
public class BridgeCrossingPortImpl implements BridgeCrossingWS {

    private static final Logger LOG = Logger.getLogger(BridgeCrossingPortImpl.class.getName());

    /* (non-Javadoc)
     * @see com.crossing.bridgecrossingws.BridgeCrossingWS#sendCrossingDetails(java.lang.String  vrn ,)java.lang.String  gateno ,)java.lang.String  direction )*
     */
    public java.lang.String sendCrossingDetails(java.lang.String vrn,java.lang.String gateno,java.lang.String direction) { 
        LOG.info("Executing operation sendCrossingDetails");
        System.out.println(vrn);
        System.out.println(gateno);
        System.out.println(direction);
        try {
            java.lang.String _return = "vrn  ::"+vrn+"   gateno::: "+gateno+"  direction::   "+direction;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
