package com.itf.vehicle.casefile;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.2
 * 2015-09-08T17:37:53.181+01:00
 * Generated source version: 3.1.2
 * 
 */
@WebService(targetNamespace = "http://casefile.Vehicle.itf.com/", name = "DocumentUploadServicePortType")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface DocumentUploadServicePortType {

    @WebResult(name = "VehicleExistsResponse", targetNamespace = "http://casefile.Vehicle.itf.com/", partName = "VehicleExistsResponse")
    @WebMethod(operationName = "VehicleExist", action = "http://casefile.Vehicle.itf.com/VehicleExist")
    public VehicleExistsResponse vehicleExist(
        @WebParam(partName = "vehicleExistenceLookupRequest", name = "vehicleExistenceLookupRequest", targetNamespace = "http://casefile.Vehicle.itf.com/")
        VehicleExistenceLookupRequest vehicleExistenceLookupRequest
    );
}
