
package com.itf.vehicle.casefile;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.2
 * 2015-09-08T17:37:53.025+01:00
 * Generated source version: 3.1.2
 * 
 */
public final class DocumentUploadServicePortType_UploadProcessorPort_Client {

    private static final QName SERVICE_NAME = new QName("http://casefile.Vehicle.itf.com/", "UploadProcessorService");

    private DocumentUploadServicePortType_UploadProcessorPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = UploadProcessorService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        UploadProcessorService ss = new UploadProcessorService(wsdlURL, SERVICE_NAME);
        DocumentUploadServicePortType port = ss.getUploadProcessorPort();  
        
        {
        System.out.println("Invoking vehicleExist...");
        com.itf.vehicle.casefile.VehicleExistenceLookupRequest _vehicleExist_vehicleExistenceLookupRequest = new com.itf.vehicle.casefile.VehicleExistenceLookupRequest();
        _vehicleExist_vehicleExistenceLookupRequest.setVehicleUniqueReference("VehicleUniqueReference-1916357020");
        com.itf.vehicle.casefile.VehicleExistsResponse _vehicleExist__return = port.vehicleExist(_vehicleExist_vehicleExistenceLookupRequest);
        System.out.println("vehicleExist.result=" + _vehicleExist__return);


        }

        System.exit(0);
    }

}
